name: Real Life Church
favicon: null
layout_spectrum: 0.02132275770418346
typography_spectrum: 0.4536236166022718
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6533313863910735
  lightness: 0.4900239505805075
  saturation: 0.25389167852699757
  rhythmicContrast: 0.7893882426433265
purpose: []
