typography_spectrum: 0.39196
color:
  brandColors:
    - '#b2b3b7'
    - '#3c4043'
    - '#070707'
    - '#f5343c'
    - '#951b21'
  brandStrength: 0.6533313863910735
  lightness: 0.4900239505805075
  saturation: 0.25389167852699757
  rhythmicContrast: 0.7893882426433265
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.27758
analytics:
  google: null
  facebook: null
  twitter: null
name: Real Life Church
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Real Life Church
description: Love God. Love People. Serve the World
purpose: []
